### ISSUE TITLE
Add a coin supply counter to the block explorer

### ISSUE THREAD

**Issue by Entity325** [decred/insight#1]
Would be useful for getting market cap info among other things. Coin indexes will want to be able to access the current coin supply.

**Comment by alexlyp** [comment]
Ya it will be added to block explorer, though I think we are going to add an RPC to daemon to pull it.  Then block explorer or anyone with a running daemon can get it.  

Problem is the easy way to do it (iterate over all blocks and count up coinbases) is only doable at small block counts.  As the chain grows, this will become more and more expensive.  

So... there is a big db change branch coming from btcd upstream.  the rough plan is to add coin supply when that branch comes in so it will not be as expensive to calculate.  

We should have that RPC done sometime next week I think.
