### ISSUE TITLE
Shows wrong block timestamp

### ISSUE THREAD

**Issue by raedah** [decred/insight#16]
Looking at this block, says Timestamp Apr 21, 2016 7:30:46 AM
https://mainnet.decred.org/block/00000000000027d17eb089a438675baa194bcda21029afa7a8692230f2b36f3d
transactions within it all say mined Apr 21, 2016 7:30:46 AM  as well.

Yimp also shows Time 2016-04-21 16:30:46 for the same block
Blockhash:	00000000000027d17eb089a438675baa194bcda21029afa7a8692230f2b36f3d
http://yiimp.ccminer.org/explorer?id=1574&height=21267

But, here is the bug, https://mainnet.decred.org/blocks
going down the list, block 21267 says Apr 21, 2016 7:31:05 AM
and most all the other blocks listed look to have a skewed time as well.

**Comment by dajohi** [comment]
This has been fixed.
