### ISSUE TITLE
Block 1 shows value error

### ISSUE THREAD

**Issue by davecgh** [decred/insight#3]
As the title indicates, blocks 0 and 1 in the block explorer sometimes show "value error" for the block reward field.

I imagine this is because of the special nature of the blocks where the genesis block has no subsidy and the block 1 is the block in which all of the initial airdrop and dev coins were created.

**Comment by alexlyp** [comment]
I believe this will be fixed with the coming update, but will leave this issue open until that is confirmed

**Comment by alexlyp** [comment]
Confirmed.
https://mainnet.decred.org/block/000000000000437482b6d47f82f374cde539440ddb108b0a76886f0d87d126b9

Shows the proper block reward.

**Comment by davecgh** [comment]
Block 0 is still showing `value error`.

**Comment by alexlyp** [comment]
K now block 0 is showing value 0 and block 1 is showing 1680000 DCR for mainnet 100000 for testnet
