### ISSUE TITLE
show expire when available

### ISSUE THREAD

**Issue by raedah** [decred/insight#33]
when displaying a ticket that has an expiration

**Comment by YSTomar** [comment]
@raedah I hope we need to display expire and locked funds for the transaction in blocks and transaction the pages(i.e. https://mainnet.decred.org/block/0000000000000043312d808807212d1cd544abea3ee0a05e398e52c90c9d91cb and https://mainnet.decred.org/tx/ac1179cbcd4961df61e5d4c9231dd31e4146e78e113a0e7068a05efd9e6533b6), Please let me know your thought.

**Comment by alexlyp** [comment]
Now that the ticket price algorithm has been updated this is no longer necessary since blocks are rarely full and tickets will no longer ever need an expiration to be set.
